server {
    listen 80;
    server_name storify.cloudedata.in;

    # 1. FRONTEND: SuperAdmin Panel Static Files
    root /var/www/Shopify_Clone/superadmin-frontend/dist;
    index index.html;

    # React Router routes support
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Redirect logs
    access_log /var/log/nginx/storify-superadmin-access.log;
    error_log /var/log/nginx/storify-superadmin-error.log;
}
