export const AUDIT_ACTIONS = [
    'THEME_INSTALLED',
    'THEME_SELECTED',
    'THEME_UPGRADED',
    'THEME_MIGRATED',
    'THEME_PUBLISHED',
    'THEME_ROLLED_BACK',
    'THEME_PREVIEWED',
    'THEME_ACTIVATED',
    'THEME_UPDATED',
    'THEME_REMOVED',
    'EXPERIMENT_CREATED',
    'EXPERIMENT_STARTED',
    'EXPERIMENT_PAUSED',
    'EXPERIMENT_COMPLETED',
    'EXPERIMENT_CANCELLED',
    'EXPERIMENT_AUTO_COMPLETED',
    'EXPERIMENT_WINNER_APPLIED',
    'CONSENT_UPDATED',
    'ANALYTICS_ATTRIBUTION_CREATED',
];

export default AUDIT_ACTIONS;
